services:

  bpmn_assistant:
    build:
      context: .
      dockerfile: ./src/bpmn_assistant/Dockerfile
    ports:
        - "8002:8000"
    environment:
        AZURE_API_KEY: ${AZURE_API_KEY}
        AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
        AZURE_OPENAI_DEPLOYMENT: ${AZURE_OPENAI_DEPLOYMENT}
        ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    networks:
      - bpmn-network

  bpmn_layout_server:
    build:
      context: .
      dockerfile: ./src/bpmn_layout_server/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - bpmn-network

  bpmn_frontend:
    build:
      context: .
      dockerfile: ./src/bpmn_frontend/Dockerfile
      args: 
        VITE_API_BASE_URL: "http://10.10.0.122:8002"
        VITE_LAYOUT_BASE_URL: "http://10.10.0.122:3001"
    ports:
      - "8080:80"
    depends_on:
      - bpmn_assistant
      - bpmn_layout_server
    networks:
        - bpmn-network

networks:
  bpmn-network:
    driver: bridge
