import json
import xml.etree.ElementTree as ET

from bpmn_assistant.config import logger
from bpmn_assistant.services import BpmnProcessTransformer


class BpmnXmlGenerator:
    """
    Class to generate BPMN XML from the BPMN process data in JSON format.
    """

    def __init__(self):
        self.transformer = BpmnProcessTransformer()

    def create_bpmn_xml(self, process: list[dict]) -> str:
        """
        Create BPMN XML from the process data.

        Args:
            process: BPMN process structure generated by the LLM.

        Returns:
            The BPMN XML string.
        """

        transformed_process = self.transformer.transform(process)

        logger.debug(
            f"Transformed process:\n{json.dumps(transformed_process, indent=2)}"
        )

        # ------------------------------------------------------------
        # Determine optional pool name
        # ------------------------------------------------------------

        pool_name = None

        for element in transformed_process["elements"]:
            if element.get("pool"):
                pool_name = element["pool"]
                break

        # ------------------------------------------------------------
        # Determine lanes in order of first appearance
        # ------------------------------------------------------------

        lane_names = []

        for element in transformed_process["elements"]:
            lane = element.get("lane")

            if lane and lane not in lane_names:
                lane_names.append(lane)

        # ------------------------------------------------------------
        # Create definitions
        # ------------------------------------------------------------

        root = ET.Element("definitions")
        root.set(
            "xmlns",
            "http://www.omg.org/spec/BPMN/20100524/MODEL",
        )
        root.set(
            "xmlns:bpmndi",
            "http://www.omg.org/spec/BPMN/20100524/DI",
        )
        root.set(
            "xmlns:dc",
            "http://www.omg.org/spec/DD/20100524/DC",
        )
        root.set(
            "xmlns:di",
            "http://www.omg.org/spec/DD/20100524/DI",
        )
        root.set("id", "definitions_1")
        root.set(
            "targetNamespace",
            "http://bpmn-assistant.swbebra.local/bpmn",
        )

        # ------------------------------------------------------------
        # Create collaboration + participant if lanes exist
        # ------------------------------------------------------------

        if lane_names:
            collaboration = ET.SubElement(
                root,
                "collaboration",
            )
            collaboration.set(
                "id",
                "Collaboration_1",
            )

            participant = ET.SubElement(
                collaboration,
                "participant",
            )
            participant.set(
                "id",
                "Participant_1",
            )
            participant.set(
                "name",
                pool_name or "BPMN Process",
            )
            participant.set(
                "processRef",
                "Process_1",
            )

        # ------------------------------------------------------------
        # Create process
        # ------------------------------------------------------------

        process_element = ET.SubElement(
            root,
            "process",
        )
        process_element.set(
            "id",
            "Process_1",
        )
        process_element.set(
            "isExecutable",
            "false",
        )

        # ------------------------------------------------------------
        # Create laneSet + lanes
        # ------------------------------------------------------------

        if lane_names:
            lane_set = ET.SubElement(
                process_element,
                "laneSet",
            )
            lane_set.set(
                "id",
                "LaneSet_1",
            )

            for index, lane_name in enumerate(
                lane_names,
                start=1,
            ):
                lane_element = ET.SubElement(
                    lane_set,
                    "lane",
                )
                lane_element.set(
                    "id",
                    f"Lane_{index}",
                )
                lane_element.set(
                    "name",
                    lane_name,
                )

                for element in transformed_process["elements"]:
                    if element.get("lane") == lane_name:
                        flow_node_ref = ET.SubElement(
                            lane_element,
                            "flowNodeRef",
                        )
                        flow_node_ref.text = element["id"]

        # ------------------------------------------------------------
        # Add BPMN elements
        # ------------------------------------------------------------

        for element in transformed_process["elements"]:
            elem = ET.SubElement(
                process_element,
                element["type"],
            )

            elem.set(
                "id",
                element["id"],
            )

            # Add label if it exists
            if element.get("label"):
                elem.set(
                    "name",
                    element["label"],
                )

            # Add default flow attribute for inclusive/exclusive gateways
            if element.get("default_flow"):
                elem.set(
                    "default",
                    element["default_flow"],
                )

            # Add incoming flows
            for incoming in element["incoming"]:
                ET.SubElement(
                    elem,
                    "incoming",
                ).text = incoming

            # Add outgoing flows
            for outgoing in element["outgoing"]:
                ET.SubElement(
                    elem,
                    "outgoing",
                ).text = outgoing

            # Add event definition
            if element.get("eventDefinition"):
                event_def_type = element["eventDefinition"]

                event_def_elem = ET.SubElement(
                    elem,
                    event_def_type,
                )

                event_def_elem.set(
                    "id",
                    f"{event_def_type}_{element['id']}",
                )

        # ------------------------------------------------------------
        # Add sequence flows
        # ------------------------------------------------------------

        for flow in transformed_process["flows"]:
            seq_flow = ET.SubElement(
                process_element,
                "sequenceFlow",
            )

            seq_flow.set(
                "id",
                flow["id"],
            )
            seq_flow.set(
                "sourceRef",
                flow["sourceRef"],
            )
            seq_flow.set(
                "targetRef",
                flow["targetRef"],
            )

            if flow.get("condition"):
                seq_flow.set(
                    "name",
                    flow["condition"],
                )

        # ------------------------------------------------------------
        # Convert XML tree to string
        # ------------------------------------------------------------

        xml_string = ET.tostring(
            root,
            encoding="unicode",
        )

        return xml_string
